# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 860)
        MainWindow.setStyleSheet("\n"
"QMainWindow, QWidget {\n"
"    background-color: #0d0d0d;\n"
"    color: #ffffff;\n"
"    font-family: \"Segoe UI\", \"system-ui\", sans-serif;\n"
"    font-size: 10.5pt;\n"
"}\n"
"\n"
"/* ---------- Tabs ---------- */\n"
"QTabWidget::pane {\n"
"    border: 1px solid rgba(255,255,255,0.12);\n"
"    border-radius: 10px;\n"
"    top: -1px;\n"
"    background: #1a1a19;\n"
"}\n"
"QTabBar::tab {\n"
"    background: transparent;\n"
"    color: #c3c2b7;\n"
"    padding: 10px 18px;\n"
"    margin-right: 4px;\n"
"    border-top-left-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"    font-weight: 600;\n"
"}\n"
"QTabBar::tab:hover {\n"
"    color: #ffffff;\n"
"    background: #242422;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    color: #ffffff;\n"
"    background: #1a1a19;\n"
"    border: 1px solid rgba(255,255,255,0.12);\n"
"    border-bottom: 3px solid #3987e5;\n"
"}\n"
"\n"
"/* ---------- Group boxes (section cards) ---------- */\n"
"QGroupBox {\n"
"    background: #1a1a19;\n"
"    border: 1px solid rgba(255,255,255,0.12);\n"
"    border-radius: 10px;\n"
"    margin-top: 14px;\n"
"    padding: 14px 10px 10px 10px;\n"
"    font-weight: 600;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 12px;\n"
"    top: 2px;\n"
"    padding: 0 6px;\n"
"    color: #3987e5;\n"
"}\n"
"\n"
"/* ---------- Buttons ---------- */\n"
"QPushButton {\n"
"    background-color: #3987e5;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5598e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5598e7;\n"
"    padding-top: 9px;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #242422;\n"
"    color: #898781;\n"
"}\n"
"\n"
"/* ---------- Inputs ---------- */\n"
"QLineEdit, QComboBox, QDoubleSpinBox, QSpinBox, QTextEdit {\n"
"    background-color: #1a1a19;\n"
"    color: #ffffff;\n"
"    border: 1px solid rgba(255,255,255,0.12);\n"
"    border-radius: 6px;\n"
"    padding: 5px 8px;\n"
"    selection-background-color: #3987e5;\n"
"}\n"
"QLineEdit:focus, QComboBox:focus, QDoubleSpinBox:focus, QSpinBox:focus, QTextEdit:focus {\n"
"    border: 1px solid #3987e5;\n"
"}\n"
"QLineEdit:disabled, QComboBox:disabled, QSpinBox:disabled {\n"
"    color: #898781;\n"
"    background-color: #242422;\n"
"}\n"
"QComboBox::drop-down { border: none; width: 22px; }\n"
"QCheckBox, QLabel { color: #ffffff; }\n"
"QCheckBox::indicator {\n"
"    width: 16px; height: 16px; border-radius: 4px;\n"
"    border: 1px solid rgba(255,255,255,0.12);\n"
"    background: #1a1a19;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: #3987e5;\n"
"    border: 1px solid #3987e5;\n"
"}\n"
"\n"
"/* ---------- Progress bar ---------- */\n"
"QProgressBar {\n"
"    background-color: #242422;\n"
"    border: 1px solid rgba(255,255,255,0.12);\n"
"    border-radius: 8px;\n"
"    height: 18px;\n"
"    text-align: center;\n"
"    color: #ffffff;\n"
"    font-weight: 600;\n"
"}\n"
"QProgressBar::chunk {\n"
"    border-radius: 7px;\n"
"    background-color: #3987e5;\n"
"}\n"
"\n"
"/* ---------- Tables ---------- */\n"
"QTableView, QTableWidget {\n"
"    background-color: #1a1a19;\n"
"    alternate-background-color: #242422;\n"
"    gridline-color: #2c2c2a;\n"
"    border: 1px solid rgba(255,255,255,0.12);\n"
"    border-radius: 8px;\n"
"    selection-background-color: #3987e5;\n"
"    selection-color: #ffffff;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #242422;\n"
"    color: #c3c2b7;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    border-bottom: 2px solid #3987e5;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* ---------- Splitters / scrollbars ---------- */\n"
"QSplitter::handle {\n"
"    background: rgba(255,255,255,0.12);\n"
"}\n"
"QSplitter::handle:hover {\n"
"    background: #3987e5;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 10px;\n"
"    margin: 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(255,255,255,0.12);\n"
"    border-radius: 5px;\n"
"    min-height: 24px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #3987e5;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    height: 10px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgba(255,255,255,0.12);\n"
"    border-radius: 5px;\n"
"    min-width: 24px;\n"
"}\n"
"QScrollBar::add-line, QScrollBar::sub-line { height: 0; width: 0; }\n"
"\n"
"/* ---------- Status bar ---------- */\n"
"QStatusBar {\n"
"    background: #1a1a19;\n"
"    color: #c3c2b7;\n"
"}\n"
"\n"
"/* ---------- Stat cards (summary frames) ---------- */\n"
"QFrame#frameTotalSamples, QFrame#frameMatchedSamples, QFrame#frameMAE,\n"
"QFrame#frameMaxError, QFrame#frameRMSE, QFrame#frameMatchPercentage {\n"
"    background: #1a1a19;\n"
"    border: 1px solid rgba(255,255,255,0.12);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QFrame#frameTotalSamples { border-left: 4px solid #3987e5; }\n"
"QFrame#frameMatchedSamples { border-left: 4px solid #199e70; }\n"
"QFrame#frameMAE { border-left: 4px solid #9085e9; }\n"
"QFrame#frameMaxError { border-left: 4px solid #d95926; }\n"
"QFrame#frameRMSE { border-left: 4px solid #d55181; }\n"
"QFrame#frameMatchPercentage { border-left: 4px solid #0ca30c; }\n"
"\n"
"QLabel#labelTotalSamplesTitle, QLabel#labelMatchedSamplesTitle, QLabel#labelMAETitle,\n"
"QLabel#labelMaxErrorTitle, QLabel#labelRMSETitle, QLabel#labelMatchPercentageTitle {\n"
"    color: #898781;\n"
"    font-weight: 600;\n"
"    font-size: 9pt;\n"
"}\n"
"QLabel#labelTotalSamplesValue, QLabel#labelMatchedSamplesValue, QLabel#labelMAEValue,\n"
"QLabel#labelMaxErrorValue, QLabel#labelRMSEValue, QLabel#labelMatchPercentageValue {\n"
"    font-size: 22px;\n"
"    font-weight: 700;\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.centralLayout.setObjectName("centralLayout")
        self.tabWidgetMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetMain.setObjectName("tabWidgetMain")
        self.tabLoadExtract = QtWidgets.QWidget()
        self.tabLoadExtract.setObjectName("tabLoadExtract")
        self.verticalLayoutLoad = QtWidgets.QVBoxLayout(self.tabLoadExtract)
        self.verticalLayoutLoad.setObjectName("verticalLayoutLoad")
        self.groupBoxTwinCsvSource = QtWidgets.QGroupBox(self.tabLoadExtract)
        self.groupBoxTwinCsvSource.setObjectName("groupBoxTwinCsvSource")
        self.verticalLayoutTwinCsvSource = QtWidgets.QVBoxLayout(self.groupBoxTwinCsvSource)
        self.verticalLayoutTwinCsvSource.setObjectName("verticalLayoutTwinCsvSource")
        self.horizontalLayoutTwinCsvBrowse = QtWidgets.QHBoxLayout()
        self.horizontalLayoutTwinCsvBrowse.setObjectName("horizontalLayoutTwinCsvBrowse")
        self.btnBrowseTwinCsv = QtWidgets.QPushButton(self.groupBoxTwinCsvSource)
        self.btnBrowseTwinCsv.setObjectName("btnBrowseTwinCsv")
        self.horizontalLayoutTwinCsvBrowse.addWidget(self.btnBrowseTwinCsv)
        self.lineEditTwinCsvPath = QtWidgets.QLineEdit(self.groupBoxTwinCsvSource)
        self.lineEditTwinCsvPath.setReadOnly(True)
        self.lineEditTwinCsvPath.setObjectName("lineEditTwinCsvPath")
        self.horizontalLayoutTwinCsvBrowse.addWidget(self.lineEditTwinCsvPath)
        self.verticalLayoutTwinCsvSource.addLayout(self.horizontalLayoutTwinCsvBrowse)
        self.labelTwinCsvInfo = QtWidgets.QLabel(self.groupBoxTwinCsvSource)
        self.labelTwinCsvInfo.setObjectName("labelTwinCsvInfo")
        self.verticalLayoutTwinCsvSource.addWidget(self.labelTwinCsvInfo)
        self.verticalLayoutLoad.addWidget(self.groupBoxTwinCsvSource)
        self.groupBoxEcuSource = QtWidgets.QGroupBox(self.tabLoadExtract)
        self.groupBoxEcuSource.setObjectName("groupBoxEcuSource")
        self.verticalLayoutEcuSource = QtWidgets.QVBoxLayout(self.groupBoxEcuSource)
        self.verticalLayoutEcuSource.setObjectName("verticalLayoutEcuSource")
        self.horizontalLayoutEcuBrowse = QtWidgets.QHBoxLayout()
        self.horizontalLayoutEcuBrowse.setObjectName("horizontalLayoutEcuBrowse")
        self.btnBrowseEcu = QtWidgets.QPushButton(self.groupBoxEcuSource)
        self.btnBrowseEcu.setObjectName("btnBrowseEcu")
        self.horizontalLayoutEcuBrowse.addWidget(self.btnBrowseEcu)
        self.lineEditEcuPath = QtWidgets.QLineEdit(self.groupBoxEcuSource)
        self.lineEditEcuPath.setReadOnly(True)
        self.lineEditEcuPath.setObjectName("lineEditEcuPath")
        self.horizontalLayoutEcuBrowse.addWidget(self.lineEditEcuPath)
        self.verticalLayoutEcuSource.addLayout(self.horizontalLayoutEcuBrowse)
        self.labelEcuInfo = QtWidgets.QLabel(self.groupBoxEcuSource)
        self.labelEcuInfo.setObjectName("labelEcuInfo")
        self.verticalLayoutEcuSource.addWidget(self.labelEcuInfo)
        self.verticalLayoutLoad.addWidget(self.groupBoxEcuSource)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutLoad.addItem(spacerItem)
        self.horizontalLayoutStartComparison = QtWidgets.QHBoxLayout()
        self.horizontalLayoutStartComparison.setObjectName("horizontalLayoutStartComparison")
        self.btnStartComparison = QtWidgets.QPushButton(self.tabLoadExtract)
        self.btnStartComparison.setEnabled(False)
        self.btnStartComparison.setMinimumSize(QtCore.QSize(0, 36))
        self.btnStartComparison.setObjectName("btnStartComparison")
        self.horizontalLayoutStartComparison.addWidget(self.btnStartComparison)
        self.progressBarComparison = QtWidgets.QProgressBar(self.tabLoadExtract)
        self.progressBarComparison.setProperty("value", 0)
        self.progressBarComparison.setObjectName("progressBarComparison")
        self.horizontalLayoutStartComparison.addWidget(self.progressBarComparison)
        self.verticalLayoutLoad.addLayout(self.horizontalLayoutStartComparison)
        self.labelModeIndicator = QtWidgets.QLabel(self.tabLoadExtract)
        self.labelModeIndicator.setWordWrap(True)
        self.labelModeIndicator.setObjectName("labelModeIndicator")
        self.verticalLayoutLoad.addWidget(self.labelModeIndicator)
        self.tabWidgetMain.addTab(self.tabLoadExtract, "")
        self.tabPreview = QtWidgets.QWidget()
        self.tabPreview.setObjectName("tabPreview")
        self.verticalLayoutPreview = QtWidgets.QVBoxLayout(self.tabPreview)
        self.verticalLayoutPreview.setObjectName("verticalLayoutPreview")
        self.splitterPreview = QtWidgets.QSplitter(self.tabPreview)
        self.splitterPreview.setOrientation(QtCore.Qt.Horizontal)
        self.splitterPreview.setObjectName("splitterPreview")
        self.groupBoxTwinPreview = QtWidgets.QGroupBox(self.splitterPreview)
        self.groupBoxTwinPreview.setObjectName("groupBoxTwinPreview")
        self.verticalLayoutTwinPreview = QtWidgets.QVBoxLayout(self.groupBoxTwinPreview)
        self.verticalLayoutTwinPreview.setObjectName("verticalLayoutTwinPreview")
        self.labelTwinPreviewInfo = QtWidgets.QLabel(self.groupBoxTwinPreview)
        self.labelTwinPreviewInfo.setObjectName("labelTwinPreviewInfo")
        self.verticalLayoutTwinPreview.addWidget(self.labelTwinPreviewInfo)
        self.tableWidgetTwinPreview = QtWidgets.QTableWidget(self.groupBoxTwinPreview)
        self.tableWidgetTwinPreview.setObjectName("tableWidgetTwinPreview")
        self.tableWidgetTwinPreview.setColumnCount(0)
        self.tableWidgetTwinPreview.setRowCount(0)
        self.verticalLayoutTwinPreview.addWidget(self.tableWidgetTwinPreview)
        self.groupBoxEcuPreview = QtWidgets.QGroupBox(self.splitterPreview)
        self.groupBoxEcuPreview.setObjectName("groupBoxEcuPreview")
        self.verticalLayoutEcuPreview = QtWidgets.QVBoxLayout(self.groupBoxEcuPreview)
        self.verticalLayoutEcuPreview.setObjectName("verticalLayoutEcuPreview")
        self.labelEcuPreviewInfo = QtWidgets.QLabel(self.groupBoxEcuPreview)
        self.labelEcuPreviewInfo.setObjectName("labelEcuPreviewInfo")
        self.verticalLayoutEcuPreview.addWidget(self.labelEcuPreviewInfo)
        self.tableWidgetEcuPreview = QtWidgets.QTableWidget(self.groupBoxEcuPreview)
        self.tableWidgetEcuPreview.setObjectName("tableWidgetEcuPreview")
        self.tableWidgetEcuPreview.setColumnCount(0)
        self.tableWidgetEcuPreview.setRowCount(0)
        self.verticalLayoutEcuPreview.addWidget(self.tableWidgetEcuPreview)
        self.verticalLayoutPreview.addWidget(self.splitterPreview)
        self.tabWidgetMain.addTab(self.tabPreview, "")
        self.tabStatistics = QtWidgets.QWidget()
        self.tabStatistics.setObjectName("tabStatistics")
        self.verticalLayoutStatistics = QtWidgets.QVBoxLayout(self.tabStatistics)
        self.verticalLayoutStatistics.setObjectName("verticalLayoutStatistics")
        self.groupBoxSummaryCards = QtWidgets.QGroupBox(self.tabStatistics)
        self.groupBoxSummaryCards.setObjectName("groupBoxSummaryCards")
        self.horizontalLayoutSummaryCards = QtWidgets.QHBoxLayout(self.groupBoxSummaryCards)
        self.horizontalLayoutSummaryCards.setObjectName("horizontalLayoutSummaryCards")
        self.frameTotalSamples = QtWidgets.QFrame(self.groupBoxSummaryCards)
        self.frameTotalSamples.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTotalSamples.setObjectName("frameTotalSamples")
        self.verticalLayoutTotalSamples = QtWidgets.QVBoxLayout(self.frameTotalSamples)
        self.verticalLayoutTotalSamples.setObjectName("verticalLayoutTotalSamples")
        self.labelTotalSamplesTitle = QtWidgets.QLabel(self.frameTotalSamples)
        self.labelTotalSamplesTitle.setObjectName("labelTotalSamplesTitle")
        self.verticalLayoutTotalSamples.addWidget(self.labelTotalSamplesTitle)
        self.labelTotalSamplesValue = QtWidgets.QLabel(self.frameTotalSamples)
        self.labelTotalSamplesValue.setObjectName("labelTotalSamplesValue")
        self.verticalLayoutTotalSamples.addWidget(self.labelTotalSamplesValue)
        self.horizontalLayoutSummaryCards.addWidget(self.frameTotalSamples)
        self.frameMatchedSamples = QtWidgets.QFrame(self.groupBoxSummaryCards)
        self.frameMatchedSamples.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMatchedSamples.setObjectName("frameMatchedSamples")
        self.verticalLayoutMatchedSamples = QtWidgets.QVBoxLayout(self.frameMatchedSamples)
        self.verticalLayoutMatchedSamples.setObjectName("verticalLayoutMatchedSamples")
        self.labelMatchedSamplesTitle = QtWidgets.QLabel(self.frameMatchedSamples)
        self.labelMatchedSamplesTitle.setObjectName("labelMatchedSamplesTitle")
        self.verticalLayoutMatchedSamples.addWidget(self.labelMatchedSamplesTitle)
        self.labelMatchedSamplesValue = QtWidgets.QLabel(self.frameMatchedSamples)
        self.labelMatchedSamplesValue.setObjectName("labelMatchedSamplesValue")
        self.verticalLayoutMatchedSamples.addWidget(self.labelMatchedSamplesValue)
        self.horizontalLayoutSummaryCards.addWidget(self.frameMatchedSamples)
        self.frameMAE = QtWidgets.QFrame(self.groupBoxSummaryCards)
        self.frameMAE.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMAE.setObjectName("frameMAE")
        self.verticalLayoutMAE = QtWidgets.QVBoxLayout(self.frameMAE)
        self.verticalLayoutMAE.setObjectName("verticalLayoutMAE")
        self.labelMAETitle = QtWidgets.QLabel(self.frameMAE)
        self.labelMAETitle.setObjectName("labelMAETitle")
        self.verticalLayoutMAE.addWidget(self.labelMAETitle)
        self.labelMAEValue = QtWidgets.QLabel(self.frameMAE)
        self.labelMAEValue.setObjectName("labelMAEValue")
        self.verticalLayoutMAE.addWidget(self.labelMAEValue)
        self.horizontalLayoutSummaryCards.addWidget(self.frameMAE)
        self.frameMaxError = QtWidgets.QFrame(self.groupBoxSummaryCards)
        self.frameMaxError.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMaxError.setObjectName("frameMaxError")
        self.verticalLayoutMaxError = QtWidgets.QVBoxLayout(self.frameMaxError)
        self.verticalLayoutMaxError.setObjectName("verticalLayoutMaxError")
        self.labelMaxErrorTitle = QtWidgets.QLabel(self.frameMaxError)
        self.labelMaxErrorTitle.setObjectName("labelMaxErrorTitle")
        self.verticalLayoutMaxError.addWidget(self.labelMaxErrorTitle)
        self.labelMaxErrorValue = QtWidgets.QLabel(self.frameMaxError)
        self.labelMaxErrorValue.setObjectName("labelMaxErrorValue")
        self.verticalLayoutMaxError.addWidget(self.labelMaxErrorValue)
        self.horizontalLayoutSummaryCards.addWidget(self.frameMaxError)
        self.frameRMSE = QtWidgets.QFrame(self.groupBoxSummaryCards)
        self.frameRMSE.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRMSE.setObjectName("frameRMSE")
        self.verticalLayoutRMSE = QtWidgets.QVBoxLayout(self.frameRMSE)
        self.verticalLayoutRMSE.setObjectName("verticalLayoutRMSE")
        self.labelRMSETitle = QtWidgets.QLabel(self.frameRMSE)
        self.labelRMSETitle.setObjectName("labelRMSETitle")
        self.verticalLayoutRMSE.addWidget(self.labelRMSETitle)
        self.labelRMSEValue = QtWidgets.QLabel(self.frameRMSE)
        self.labelRMSEValue.setObjectName("labelRMSEValue")
        self.verticalLayoutRMSE.addWidget(self.labelRMSEValue)
        self.horizontalLayoutSummaryCards.addWidget(self.frameRMSE)
        self.frameMatchPercentage = QtWidgets.QFrame(self.groupBoxSummaryCards)
        self.frameMatchPercentage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMatchPercentage.setObjectName("frameMatchPercentage")
        self.verticalLayoutMatchPercentage = QtWidgets.QVBoxLayout(self.frameMatchPercentage)
        self.verticalLayoutMatchPercentage.setObjectName("verticalLayoutMatchPercentage")
        self.labelMatchPercentageTitle = QtWidgets.QLabel(self.frameMatchPercentage)
        self.labelMatchPercentageTitle.setObjectName("labelMatchPercentageTitle")
        self.verticalLayoutMatchPercentage.addWidget(self.labelMatchPercentageTitle)
        self.labelMatchPercentageValue = QtWidgets.QLabel(self.frameMatchPercentage)
        self.labelMatchPercentageValue.setObjectName("labelMatchPercentageValue")
        self.verticalLayoutMatchPercentage.addWidget(self.labelMatchPercentageValue)
        self.horizontalLayoutSummaryCards.addWidget(self.frameMatchPercentage)
        self.verticalLayoutStatistics.addWidget(self.groupBoxSummaryCards)
        self.labelPerSignalBreakdownTitle = QtWidgets.QLabel(self.tabStatistics)
        self.labelPerSignalBreakdownTitle.setObjectName("labelPerSignalBreakdownTitle")
        self.verticalLayoutStatistics.addWidget(self.labelPerSignalBreakdownTitle)
        self.tableWidgetPerSignalStats = QtWidgets.QTableWidget(self.tabStatistics)
        self.tableWidgetPerSignalStats.setObjectName("tableWidgetPerSignalStats")
        self.tableWidgetPerSignalStats.setColumnCount(0)
        self.tableWidgetPerSignalStats.setRowCount(0)
        self.verticalLayoutStatistics.addWidget(self.tableWidgetPerSignalStats)
        self.labelWorstMismatchesTitle = QtWidgets.QLabel(self.tabStatistics)
        self.labelWorstMismatchesTitle.setObjectName("labelWorstMismatchesTitle")
        self.verticalLayoutStatistics.addWidget(self.labelWorstMismatchesTitle)
        self.tableWidgetWorstMismatches = QtWidgets.QTableWidget(self.tabStatistics)
        self.tableWidgetWorstMismatches.setObjectName("tableWidgetWorstMismatches")
        self.tableWidgetWorstMismatches.setColumnCount(0)
        self.tableWidgetWorstMismatches.setRowCount(0)
        self.verticalLayoutStatistics.addWidget(self.tableWidgetWorstMismatches)
        self.tabWidgetMain.addTab(self.tabStatistics, "")
        self.tabGraphs = QtWidgets.QWidget()
        self.tabGraphs.setObjectName("tabGraphs")
        self.verticalLayoutGraphs = QtWidgets.QVBoxLayout(self.tabGraphs)
        self.verticalLayoutGraphs.setObjectName("verticalLayoutGraphs")
        self.splitterGraphs = QtWidgets.QSplitter(self.tabGraphs)
        self.splitterGraphs.setOrientation(QtCore.Qt.Vertical)
        self.splitterGraphs.setObjectName("splitterGraphs")
        self.widgetVoltagePlotContainer = QtWidgets.QWidget(self.splitterGraphs)
        self.widgetVoltagePlotContainer.setObjectName("widgetVoltagePlotContainer")
        self.verticalLayoutVoltagePlot = QtWidgets.QVBoxLayout(self.widgetVoltagePlotContainer)
        self.verticalLayoutVoltagePlot.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutVoltagePlot.setObjectName("verticalLayoutVoltagePlot")
        self.labelVoltagePlotTitle = QtWidgets.QLabel(self.widgetVoltagePlotContainer)
        self.labelVoltagePlotTitle.setObjectName("labelVoltagePlotTitle")
        self.verticalLayoutVoltagePlot.addWidget(self.labelVoltagePlotTitle)
        self.labelVoltageWarning = QtWidgets.QLabel(self.widgetVoltagePlotContainer)
        self.labelVoltageWarning.setText("")
        self.labelVoltageWarning.setWordWrap(True)
        self.labelVoltageWarning.setObjectName("labelVoltageWarning")
        self.verticalLayoutVoltagePlot.addWidget(self.labelVoltageWarning)
        self.plotWidgetVoltage = PlotWidget(self.widgetVoltagePlotContainer)
        self.plotWidgetVoltage.setObjectName("plotWidgetVoltage")
        self.verticalLayoutVoltagePlot.addWidget(self.plotWidgetVoltage)
        self.widgetCurrentPlotContainer = QtWidgets.QWidget(self.splitterGraphs)
        self.widgetCurrentPlotContainer.setObjectName("widgetCurrentPlotContainer")
        self.verticalLayoutCurrentPlot = QtWidgets.QVBoxLayout(self.widgetCurrentPlotContainer)
        self.verticalLayoutCurrentPlot.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutCurrentPlot.setObjectName("verticalLayoutCurrentPlot")
        self.labelCurrentPlotTitle = QtWidgets.QLabel(self.widgetCurrentPlotContainer)
        self.labelCurrentPlotTitle.setObjectName("labelCurrentPlotTitle")
        self.verticalLayoutCurrentPlot.addWidget(self.labelCurrentPlotTitle)
        self.labelCurrentWarning = QtWidgets.QLabel(self.widgetCurrentPlotContainer)
        self.labelCurrentWarning.setText("")
        self.labelCurrentWarning.setWordWrap(True)
        self.labelCurrentWarning.setObjectName("labelCurrentWarning")
        self.verticalLayoutCurrentPlot.addWidget(self.labelCurrentWarning)
        self.plotWidgetCurrent = PlotWidget(self.widgetCurrentPlotContainer)
        self.plotWidgetCurrent.setObjectName("plotWidgetCurrent")
        self.verticalLayoutCurrentPlot.addWidget(self.plotWidgetCurrent)
        self.widgetTemperaturePlotContainer = QtWidgets.QWidget(self.splitterGraphs)
        self.widgetTemperaturePlotContainer.setObjectName("widgetTemperaturePlotContainer")
        self.verticalLayoutTemperaturePlot = QtWidgets.QVBoxLayout(self.widgetTemperaturePlotContainer)
        self.verticalLayoutTemperaturePlot.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutTemperaturePlot.setObjectName("verticalLayoutTemperaturePlot")
        self.labelTemperaturePlotTitle = QtWidgets.QLabel(self.widgetTemperaturePlotContainer)
        self.labelTemperaturePlotTitle.setObjectName("labelTemperaturePlotTitle")
        self.verticalLayoutTemperaturePlot.addWidget(self.labelTemperaturePlotTitle)
        self.plotWidgetTemperature = PlotWidget(self.widgetTemperaturePlotContainer)
        self.plotWidgetTemperature.setObjectName("plotWidgetTemperature")
        self.verticalLayoutTemperaturePlot.addWidget(self.plotWidgetTemperature)
        self.widgetSocPlotContainer = QtWidgets.QWidget(self.splitterGraphs)
        self.widgetSocPlotContainer.setObjectName("widgetSocPlotContainer")
        self.verticalLayoutSocPlot = QtWidgets.QVBoxLayout(self.widgetSocPlotContainer)
        self.verticalLayoutSocPlot.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutSocPlot.setObjectName("verticalLayoutSocPlot")
        self.labelSocPlotTitle = QtWidgets.QLabel(self.widgetSocPlotContainer)
        self.labelSocPlotTitle.setObjectName("labelSocPlotTitle")
        self.verticalLayoutSocPlot.addWidget(self.labelSocPlotTitle)
        self.plotWidgetSoc = PlotWidget(self.widgetSocPlotContainer)
        self.plotWidgetSoc.setObjectName("plotWidgetSoc")
        self.verticalLayoutSocPlot.addWidget(self.plotWidgetSoc)
        self.widgetSohPlotContainer = QtWidgets.QWidget(self.splitterGraphs)
        self.widgetSohPlotContainer.setObjectName("widgetSohPlotContainer")
        self.verticalLayoutSohPlot = QtWidgets.QVBoxLayout(self.widgetSohPlotContainer)
        self.verticalLayoutSohPlot.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutSohPlot.setObjectName("verticalLayoutSohPlot")
        self.labelSohPlotTitle = QtWidgets.QLabel(self.widgetSohPlotContainer)
        self.labelSohPlotTitle.setObjectName("labelSohPlotTitle")
        self.verticalLayoutSohPlot.addWidget(self.labelSohPlotTitle)
        self.plotWidgetSoh = PlotWidget(self.widgetSohPlotContainer)
        self.plotWidgetSoh.setObjectName("plotWidgetSoh")
        self.verticalLayoutSohPlot.addWidget(self.plotWidgetSoh)
        self.widgetErrorPlotContainer = QtWidgets.QWidget(self.splitterGraphs)
        self.widgetErrorPlotContainer.setObjectName("widgetErrorPlotContainer")
        self.verticalLayoutErrorPlot = QtWidgets.QVBoxLayout(self.widgetErrorPlotContainer)
        self.verticalLayoutErrorPlot.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutErrorPlot.setObjectName("verticalLayoutErrorPlot")
        self.groupBoxSignalSelection = QtWidgets.QGroupBox(self.widgetErrorPlotContainer)
        self.groupBoxSignalSelection.setObjectName("groupBoxSignalSelection")
        self.horizontalLayoutSignalSelection = QtWidgets.QHBoxLayout(self.groupBoxSignalSelection)
        self.horizontalLayoutSignalSelection.setObjectName("horizontalLayoutSignalSelection")
        self.checkBoxSignalVoltage = QtWidgets.QCheckBox(self.groupBoxSignalSelection)
        self.checkBoxSignalVoltage.setChecked(True)
        self.checkBoxSignalVoltage.setObjectName("checkBoxSignalVoltage")
        self.horizontalLayoutSignalSelection.addWidget(self.checkBoxSignalVoltage)
        self.checkBoxSignalCurrent = QtWidgets.QCheckBox(self.groupBoxSignalSelection)
        self.checkBoxSignalCurrent.setChecked(True)
        self.checkBoxSignalCurrent.setObjectName("checkBoxSignalCurrent")
        self.horizontalLayoutSignalSelection.addWidget(self.checkBoxSignalCurrent)
        self.checkBoxSignalTemperature = QtWidgets.QCheckBox(self.groupBoxSignalSelection)
        self.checkBoxSignalTemperature.setChecked(True)
        self.checkBoxSignalTemperature.setObjectName("checkBoxSignalTemperature")
        self.horizontalLayoutSignalSelection.addWidget(self.checkBoxSignalTemperature)
        self.checkBoxSignalSoc = QtWidgets.QCheckBox(self.groupBoxSignalSelection)
        self.checkBoxSignalSoc.setChecked(True)
        self.checkBoxSignalSoc.setObjectName("checkBoxSignalSoc")
        self.horizontalLayoutSignalSelection.addWidget(self.checkBoxSignalSoc)
        self.checkBoxSignalSoh = QtWidgets.QCheckBox(self.groupBoxSignalSelection)
        self.checkBoxSignalSoh.setChecked(True)
        self.checkBoxSignalSoh.setObjectName("checkBoxSignalSoh")
        self.horizontalLayoutSignalSelection.addWidget(self.checkBoxSignalSoh)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutSignalSelection.addItem(spacerItem1)
        self.checkBoxSignalSelectOnly = QtWidgets.QCheckBox(self.groupBoxSignalSelection)
        self.checkBoxSignalSelectOnly.setChecked(False)
        self.checkBoxSignalSelectOnly.setObjectName("checkBoxSignalSelectOnly")
        self.horizontalLayoutSignalSelection.addWidget(self.checkBoxSignalSelectOnly)
        self.verticalLayoutErrorPlot.addWidget(self.groupBoxSignalSelection)
        self.labelErrorPlotTitle = QtWidgets.QLabel(self.widgetErrorPlotContainer)
        self.labelErrorPlotTitle.setObjectName("labelErrorPlotTitle")
        self.verticalLayoutErrorPlot.addWidget(self.labelErrorPlotTitle)
        self.plotWidgetError = PlotWidget(self.widgetErrorPlotContainer)
        self.plotWidgetError.setObjectName("plotWidgetError")
        self.verticalLayoutErrorPlot.addWidget(self.plotWidgetError)
        self.verticalLayoutGraphs.addWidget(self.splitterGraphs)
        self.tabWidgetMain.addTab(self.tabGraphs, "")
        self.tabConfig = QtWidgets.QWidget()
        self.tabConfig.setObjectName("tabConfig")
        self.verticalLayoutConfig = QtWidgets.QVBoxLayout(self.tabConfig)
        self.verticalLayoutConfig.setObjectName("verticalLayoutConfig")
        self.groupBoxTolerance = QtWidgets.QGroupBox(self.tabConfig)
        self.groupBoxTolerance.setObjectName("groupBoxTolerance")
        self.formLayoutTolerance = QtWidgets.QFormLayout(self.groupBoxTolerance)
        self.formLayoutTolerance.setObjectName("formLayoutTolerance")
        self.labelVoltageToleranceCaption = QtWidgets.QLabel(self.groupBoxTolerance)
        self.labelVoltageToleranceCaption.setObjectName("labelVoltageToleranceCaption")
        self.formLayoutTolerance.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelVoltageToleranceCaption)
        self.doubleSpinBoxVoltageTolerance = QtWidgets.QDoubleSpinBox(self.groupBoxTolerance)
        self.doubleSpinBoxVoltageTolerance.setDecimals(4)
        self.doubleSpinBoxVoltageTolerance.setMinimum(0.0)
        self.doubleSpinBoxVoltageTolerance.setMaximum(50.0)
        self.doubleSpinBoxVoltageTolerance.setSingleStep(0.01)
        self.doubleSpinBoxVoltageTolerance.setProperty("value", 2.0)
        self.doubleSpinBoxVoltageTolerance.setObjectName("doubleSpinBoxVoltageTolerance")
        self.formLayoutTolerance.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxVoltageTolerance)
        self.labelCurrentToleranceCaption = QtWidgets.QLabel(self.groupBoxTolerance)
        self.labelCurrentToleranceCaption.setObjectName("labelCurrentToleranceCaption")
        self.formLayoutTolerance.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelCurrentToleranceCaption)
        self.doubleSpinBoxCurrentTolerance = QtWidgets.QDoubleSpinBox(self.groupBoxTolerance)
        self.doubleSpinBoxCurrentTolerance.setDecimals(4)
        self.doubleSpinBoxCurrentTolerance.setMinimum(0.0)
        self.doubleSpinBoxCurrentTolerance.setMaximum(50.0)
        self.doubleSpinBoxCurrentTolerance.setSingleStep(0.01)
        self.doubleSpinBoxCurrentTolerance.setProperty("value", 2.0)
        self.doubleSpinBoxCurrentTolerance.setObjectName("doubleSpinBoxCurrentTolerance")
        self.formLayoutTolerance.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxCurrentTolerance)
        self.labelTemperatureToleranceCaption = QtWidgets.QLabel(self.groupBoxTolerance)
        self.labelTemperatureToleranceCaption.setObjectName("labelTemperatureToleranceCaption")
        self.formLayoutTolerance.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelTemperatureToleranceCaption)
        self.doubleSpinBoxTemperatureTolerance = QtWidgets.QDoubleSpinBox(self.groupBoxTolerance)
        self.doubleSpinBoxTemperatureTolerance.setDecimals(4)
        self.doubleSpinBoxTemperatureTolerance.setMinimum(0.0)
        self.doubleSpinBoxTemperatureTolerance.setMaximum(50.0)
        self.doubleSpinBoxTemperatureTolerance.setSingleStep(0.01)
        self.doubleSpinBoxTemperatureTolerance.setProperty("value", 2.0)
        self.doubleSpinBoxTemperatureTolerance.setObjectName("doubleSpinBoxTemperatureTolerance")
        self.formLayoutTolerance.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxTemperatureTolerance)
        self.verticalLayoutConfig.addWidget(self.groupBoxTolerance)
        self.groupBoxThresholdWarnings = QtWidgets.QGroupBox(self.tabConfig)
        self.groupBoxThresholdWarnings.setObjectName("groupBoxThresholdWarnings")
        self.gridLayoutThresholdWarnings = QtWidgets.QGridLayout(self.groupBoxThresholdWarnings)
        self.gridLayoutThresholdWarnings.setObjectName("gridLayoutThresholdWarnings")
        self.checkBoxEnableVoltageThreshold = QtWidgets.QCheckBox(self.groupBoxThresholdWarnings)
        self.checkBoxEnableVoltageThreshold.setObjectName("checkBoxEnableVoltageThreshold")
        self.gridLayoutThresholdWarnings.addWidget(self.checkBoxEnableVoltageThreshold, 0, 0, 1, 1)
        self.doubleSpinBoxVoltageThreshold = QtWidgets.QDoubleSpinBox(self.groupBoxThresholdWarnings)
        self.doubleSpinBoxVoltageThreshold.setEnabled(False)
        self.doubleSpinBoxVoltageThreshold.setDecimals(2)
        self.doubleSpinBoxVoltageThreshold.setMinimum(-1000.0)
        self.doubleSpinBoxVoltageThreshold.setMaximum(1000.0)
        self.doubleSpinBoxVoltageThreshold.setSingleStep(0.1)
        self.doubleSpinBoxVoltageThreshold.setProperty("value", 4.2)
        self.doubleSpinBoxVoltageThreshold.setObjectName("doubleSpinBoxVoltageThreshold")
        self.gridLayoutThresholdWarnings.addWidget(self.doubleSpinBoxVoltageThreshold, 0, 1, 1, 1)
        self.checkBoxEnableCurrentThreshold = QtWidgets.QCheckBox(self.groupBoxThresholdWarnings)
        self.checkBoxEnableCurrentThreshold.setObjectName("checkBoxEnableCurrentThreshold")
        self.gridLayoutThresholdWarnings.addWidget(self.checkBoxEnableCurrentThreshold, 1, 0, 1, 1)
        self.doubleSpinBoxCurrentThreshold = QtWidgets.QDoubleSpinBox(self.groupBoxThresholdWarnings)
        self.doubleSpinBoxCurrentThreshold.setEnabled(False)
        self.doubleSpinBoxCurrentThreshold.setDecimals(2)
        self.doubleSpinBoxCurrentThreshold.setMinimum(-1000.0)
        self.doubleSpinBoxCurrentThreshold.setMaximum(1000.0)
        self.doubleSpinBoxCurrentThreshold.setSingleStep(0.5)
        self.doubleSpinBoxCurrentThreshold.setProperty("value", 50.0)
        self.doubleSpinBoxCurrentThreshold.setObjectName("doubleSpinBoxCurrentThreshold")
        self.gridLayoutThresholdWarnings.addWidget(self.doubleSpinBoxCurrentThreshold, 1, 1, 1, 1)
        self.verticalLayoutConfig.addWidget(self.groupBoxThresholdWarnings)
        self.groupBoxAlignment = QtWidgets.QGroupBox(self.tabConfig)
        self.groupBoxAlignment.setObjectName("groupBoxAlignment")
        self.horizontalLayoutAlignment = QtWidgets.QHBoxLayout(self.groupBoxAlignment)
        self.horizontalLayoutAlignment.setObjectName("horizontalLayoutAlignment")
        self.comboBoxAlignmentMethod = QtWidgets.QComboBox(self.groupBoxAlignment)
        self.comboBoxAlignmentMethod.setObjectName("comboBoxAlignmentMethod")
        self.comboBoxAlignmentMethod.addItem("")
        self.comboBoxAlignmentMethod.addItem("")
        self.horizontalLayoutAlignment.addWidget(self.comboBoxAlignmentMethod)
        self.verticalLayoutConfig.addWidget(self.groupBoxAlignment)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutConfig.addItem(spacerItem2)
        self.btnApplyRerun = QtWidgets.QPushButton(self.tabConfig)
        self.btnApplyRerun.setMinimumSize(QtCore.QSize(0, 36))
        self.btnApplyRerun.setObjectName("btnApplyRerun")
        self.verticalLayoutConfig.addWidget(self.btnApplyRerun)
        self.tabWidgetMain.addTab(self.tabConfig, "")
        self.tabReport = QtWidgets.QWidget()
        self.tabReport.setObjectName("tabReport")
        self.verticalLayoutReport = QtWidgets.QVBoxLayout(self.tabReport)
        self.verticalLayoutReport.setObjectName("verticalLayoutReport")
        self.groupBoxExportReport = QtWidgets.QGroupBox(self.tabReport)
        self.groupBoxExportReport.setObjectName("groupBoxExportReport")
        self.horizontalLayoutExportReport = QtWidgets.QHBoxLayout(self.groupBoxExportReport)
        self.horizontalLayoutExportReport.setObjectName("horizontalLayoutExportReport")
        self.labelReportFormatCaption = QtWidgets.QLabel(self.groupBoxExportReport)
        self.labelReportFormatCaption.setObjectName("labelReportFormatCaption")
        self.horizontalLayoutExportReport.addWidget(self.labelReportFormatCaption)
        self.comboBoxReportFormat = QtWidgets.QComboBox(self.groupBoxExportReport)
        self.comboBoxReportFormat.setObjectName("comboBoxReportFormat")
        self.comboBoxReportFormat.addItem("")
        self.comboBoxReportFormat.addItem("")
        self.horizontalLayoutExportReport.addWidget(self.comboBoxReportFormat)
        self.btnExportReport = QtWidgets.QPushButton(self.groupBoxExportReport)
        self.btnExportReport.setObjectName("btnExportReport")
        self.horizontalLayoutExportReport.addWidget(self.btnExportReport)
        self.verticalLayoutReport.addWidget(self.groupBoxExportReport)
        self.groupBoxExportData = QtWidgets.QGroupBox(self.tabReport)
        self.groupBoxExportData.setObjectName("groupBoxExportData")
        self.horizontalLayoutExportData = QtWidgets.QHBoxLayout(self.groupBoxExportData)
        self.horizontalLayoutExportData.setObjectName("horizontalLayoutExportData")
        self.labelDataFormatCaption = QtWidgets.QLabel(self.groupBoxExportData)
        self.labelDataFormatCaption.setObjectName("labelDataFormatCaption")
        self.horizontalLayoutExportData.addWidget(self.labelDataFormatCaption)
        self.comboBoxDataFormat = QtWidgets.QComboBox(self.groupBoxExportData)
        self.comboBoxDataFormat.setObjectName("comboBoxDataFormat")
        self.comboBoxDataFormat.addItem("")
        self.comboBoxDataFormat.addItem("")
        self.horizontalLayoutExportData.addWidget(self.comboBoxDataFormat)
        self.btnExportData = QtWidgets.QPushButton(self.groupBoxExportData)
        self.btnExportData.setObjectName("btnExportData")
        self.horizontalLayoutExportData.addWidget(self.btnExportData)
        self.verticalLayoutReport.addWidget(self.groupBoxExportData)
        self.labelExportLogTitle = QtWidgets.QLabel(self.tabReport)
        self.labelExportLogTitle.setObjectName("labelExportLogTitle")
        self.verticalLayoutReport.addWidget(self.labelExportLogTitle)
        self.textEditExportLog = QtWidgets.QTextEdit(self.tabReport)
        self.textEditExportLog.setReadOnly(True)
        self.textEditExportLog.setObjectName("textEditExportLog")
        self.verticalLayoutReport.addWidget(self.textEditExportLog)
        self.tabWidgetMain.addTab(self.tabReport, "")
        self.tabLiveMode = QtWidgets.QWidget()
        self.tabLiveMode.setObjectName("tabLiveMode")
        self.verticalLayoutLiveMode = QtWidgets.QVBoxLayout(self.tabLiveMode)
        self.verticalLayoutLiveMode.setObjectName("verticalLayoutLiveMode")
        self.labelLiveModeInfo = QtWidgets.QLabel(self.tabLiveMode)
        self.labelLiveModeInfo.setWordWrap(True)
        self.labelLiveModeInfo.setObjectName("labelLiveModeInfo")
        self.verticalLayoutLiveMode.addWidget(self.labelLiveModeInfo)
        self.groupBoxMqttBroker = QtWidgets.QGroupBox(self.tabLiveMode)
        self.groupBoxMqttBroker.setObjectName("groupBoxMqttBroker")
        self.formLayoutMqttBroker = QtWidgets.QFormLayout(self.groupBoxMqttBroker)
        self.formLayoutMqttBroker.setObjectName("formLayoutMqttBroker")
        self.labelMqttHostCaption = QtWidgets.QLabel(self.groupBoxMqttBroker)
        self.labelMqttHostCaption.setObjectName("labelMqttHostCaption")
        self.formLayoutMqttBroker.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelMqttHostCaption)
        self.lineEditMqttHost = QtWidgets.QLineEdit(self.groupBoxMqttBroker)
        self.lineEditMqttHost.setObjectName("lineEditMqttHost")
        self.formLayoutMqttBroker.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditMqttHost)
        self.labelMqttPortCaption = QtWidgets.QLabel(self.groupBoxMqttBroker)
        self.labelMqttPortCaption.setObjectName("labelMqttPortCaption")
        self.formLayoutMqttBroker.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelMqttPortCaption)
        self.spinBoxMqttPort = QtWidgets.QSpinBox(self.groupBoxMqttBroker)
        self.spinBoxMqttPort.setMinimum(1)
        self.spinBoxMqttPort.setMaximum(65535)
        self.spinBoxMqttPort.setProperty("value", 1883)
        self.spinBoxMqttPort.setObjectName("spinBoxMqttPort")
        self.formLayoutMqttBroker.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxMqttPort)
        self.labelMqttQosCaption = QtWidgets.QLabel(self.groupBoxMqttBroker)
        self.labelMqttQosCaption.setObjectName("labelMqttQosCaption")
        self.formLayoutMqttBroker.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelMqttQosCaption)
        self.comboBoxMqttQos = QtWidgets.QComboBox(self.groupBoxMqttBroker)
        self.comboBoxMqttQos.setObjectName("comboBoxMqttQos")
        self.comboBoxMqttQos.addItem("")
        self.comboBoxMqttQos.addItem("")
        self.comboBoxMqttQos.addItem("")
        self.formLayoutMqttBroker.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBoxMqttQos)
        self.labelMqttUserCaption = QtWidgets.QLabel(self.groupBoxMqttBroker)
        self.labelMqttUserCaption.setObjectName("labelMqttUserCaption")
        self.formLayoutMqttBroker.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelMqttUserCaption)
        self.lineEditMqttUser = QtWidgets.QLineEdit(self.groupBoxMqttBroker)
        self.lineEditMqttUser.setObjectName("lineEditMqttUser")
        self.formLayoutMqttBroker.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditMqttUser)
        self.labelMqttPassCaption = QtWidgets.QLabel(self.groupBoxMqttBroker)
        self.labelMqttPassCaption.setObjectName("labelMqttPassCaption")
        self.formLayoutMqttBroker.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelMqttPassCaption)
        self.lineEditMqttPass = QtWidgets.QLineEdit(self.groupBoxMqttBroker)
        self.lineEditMqttPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditMqttPass.setObjectName("lineEditMqttPass")
        self.formLayoutMqttBroker.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditMqttPass)
        self.verticalLayoutLiveMode.addWidget(self.groupBoxMqttBroker)
        self.groupBoxMqttTopics = QtWidgets.QGroupBox(self.tabLiveMode)
        self.groupBoxMqttTopics.setObjectName("groupBoxMqttTopics")
        self.formLayoutMqttTopics = QtWidgets.QFormLayout(self.groupBoxMqttTopics)
        self.formLayoutMqttTopics.setObjectName("formLayoutMqttTopics")
        self.labelMqttTwinTopicCaption = QtWidgets.QLabel(self.groupBoxMqttTopics)
        self.labelMqttTwinTopicCaption.setObjectName("labelMqttTwinTopicCaption")
        self.formLayoutMqttTopics.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelMqttTwinTopicCaption)
        self.lineEditMqttTwinTopic = QtWidgets.QLineEdit(self.groupBoxMqttTopics)
        self.lineEditMqttTwinTopic.setObjectName("lineEditMqttTwinTopic")
        self.formLayoutMqttTopics.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditMqttTwinTopic)
        self.labelMqttEcuTopicCaption = QtWidgets.QLabel(self.groupBoxMqttTopics)
        self.labelMqttEcuTopicCaption.setObjectName("labelMqttEcuTopicCaption")
        self.formLayoutMqttTopics.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelMqttEcuTopicCaption)
        self.lineEditMqttEcuTopic = QtWidgets.QLineEdit(self.groupBoxMqttTopics)
        self.lineEditMqttEcuTopic.setObjectName("lineEditMqttEcuTopic")
        self.formLayoutMqttTopics.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditMqttEcuTopic)
        self.verticalLayoutLiveMode.addWidget(self.groupBoxMqttTopics)
        self.groupBoxLiveUpdate = QtWidgets.QGroupBox(self.tabLiveMode)
        self.groupBoxLiveUpdate.setObjectName("groupBoxLiveUpdate")
        self.formLayoutLiveUpdate = QtWidgets.QFormLayout(self.groupBoxLiveUpdate)
        self.formLayoutLiveUpdate.setObjectName("formLayoutLiveUpdate")
        self.checkBoxLiveAutoRefresh = QtWidgets.QCheckBox(self.groupBoxLiveUpdate)
        self.checkBoxLiveAutoRefresh.setChecked(True)
        self.checkBoxLiveAutoRefresh.setObjectName("checkBoxLiveAutoRefresh")
        self.formLayoutLiveUpdate.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.checkBoxLiveAutoRefresh)
        self.labelLiveIntervalCaption = QtWidgets.QLabel(self.groupBoxLiveUpdate)
        self.labelLiveIntervalCaption.setObjectName("labelLiveIntervalCaption")
        self.formLayoutLiveUpdate.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelLiveIntervalCaption)
        self.horizontalLayoutLiveInterval = QtWidgets.QHBoxLayout()
        self.horizontalLayoutLiveInterval.setObjectName("horizontalLayoutLiveInterval")
        self.spinBoxLiveInterval = QtWidgets.QSpinBox(self.groupBoxLiveUpdate)
        self.spinBoxLiveInterval.setMinimum(50)
        self.spinBoxLiveInterval.setMaximum(10000)
        self.spinBoxLiveInterval.setSingleStep(50)
        self.spinBoxLiveInterval.setProperty("value", 500)
        self.spinBoxLiveInterval.setObjectName("spinBoxLiveInterval")
        self.horizontalLayoutLiveInterval.addWidget(self.spinBoxLiveInterval)
        self.labelLiveIntervalUnit = QtWidgets.QLabel(self.groupBoxLiveUpdate)
        self.labelLiveIntervalUnit.setObjectName("labelLiveIntervalUnit")
        self.horizontalLayoutLiveInterval.addWidget(self.labelLiveIntervalUnit)
        self.formLayoutLiveUpdate.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayoutLiveInterval)
        self.verticalLayoutLiveMode.addWidget(self.groupBoxLiveUpdate)
        self.horizontalLayoutLiveControls = QtWidgets.QHBoxLayout()
        self.horizontalLayoutLiveControls.setObjectName("horizontalLayoutLiveControls")
        self.btnLiveConnect = QtWidgets.QPushButton(self.tabLiveMode)
        self.btnLiveConnect.setMinimumSize(QtCore.QSize(0, 36))
        self.btnLiveConnect.setCheckable(True)
        self.btnLiveConnect.setObjectName("btnLiveConnect")
        self.horizontalLayoutLiveControls.addWidget(self.btnLiveConnect)
        self.labelLiveStatus = QtWidgets.QLabel(self.tabLiveMode)
        self.labelLiveStatus.setObjectName("labelLiveStatus")
        self.horizontalLayoutLiveControls.addWidget(self.labelLiveStatus)
        self.btnLiveSnapshot = QtWidgets.QPushButton(self.tabLiveMode)
        self.btnLiveSnapshot.setObjectName("btnLiveSnapshot")
        self.horizontalLayoutLiveControls.addWidget(self.btnLiveSnapshot)
        self.verticalLayoutLiveMode.addLayout(self.horizontalLayoutLiveControls)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutLiveMode.addItem(spacerItem3)
        self.tabWidgetMain.addTab(self.tabLiveMode, "")
        self.tabEvents = QtWidgets.QWidget()
        self.tabEvents.setObjectName("tabEvents")
        self.verticalLayoutEvents = QtWidgets.QVBoxLayout(self.tabEvents)
        self.verticalLayoutEvents.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutEvents.setObjectName("verticalLayoutEvents")
        self.tabWidgetMain.addTab(self.tabEvents, "")
        self.centralLayout.addWidget(self.tabWidgetMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Digital Twin Validation Tool — Twin (Simulink) vs ECU (NXP MPC5744P)"))
        self.groupBoxTwinCsvSource.setTitle(_translate("MainWindow", "Digital Twin Output (CSV)"))
        self.btnBrowseTwinCsv.setText(_translate("MainWindow", "Browse Digital Twin CSV..."))
        self.lineEditTwinCsvPath.setPlaceholderText(_translate("MainWindow", "No Digital Twin CSV selected"))
        self.labelTwinCsvInfo.setText(_translate("MainWindow", "No file loaded."))
        self.groupBoxEcuSource.setTitle(_translate("MainWindow", "NXP MPC5744P / ECU Output (CSV)"))
        self.btnBrowseEcu.setText(_translate("MainWindow", "Browse ECU CSV..."))
        self.lineEditEcuPath.setPlaceholderText(_translate("MainWindow", "No ECU CSV selected"))
        self.labelEcuInfo.setText(_translate("MainWindow", "No file loaded."))
        self.btnStartComparison.setText(_translate("MainWindow", "Start Comparison"))
        self.labelModeIndicator.setText(_translate("MainWindow", "Mode: Offline (CSV) — load both files, then Start Comparison. Use Tab 7 (Live) to stream over MQTT instead."))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabLoadExtract), _translate("MainWindow", "📥  Load & Extract"))
        self.groupBoxTwinPreview.setTitle(_translate("MainWindow", "Digital Twin Data Preview"))
        self.labelTwinPreviewInfo.setText(_translate("MainWindow", "0 rows"))
        self.groupBoxEcuPreview.setTitle(_translate("MainWindow", "ECU Data Preview"))
        self.labelEcuPreviewInfo.setText(_translate("MainWindow", "0 rows"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabPreview), _translate("MainWindow", "👁  Preview"))
        self.groupBoxSummaryCards.setTitle(_translate("MainWindow", "Comparison Summary"))
        self.labelTotalSamplesTitle.setText(_translate("MainWindow", "Total Samples"))
        self.labelTotalSamplesValue.setText(_translate("MainWindow", "--"))
        self.labelMatchedSamplesTitle.setText(_translate("MainWindow", "Aligned / Matched"))
        self.labelMatchedSamplesValue.setText(_translate("MainWindow", "--"))
        self.labelMAETitle.setText(_translate("MainWindow", "Mean Abs Error"))
        self.labelMAEValue.setText(_translate("MainWindow", "--"))
        self.labelMaxErrorTitle.setText(_translate("MainWindow", "Max Error"))
        self.labelMaxErrorValue.setText(_translate("MainWindow", "--"))
        self.labelRMSETitle.setText(_translate("MainWindow", "RMSE"))
        self.labelRMSEValue.setText(_translate("MainWindow", "--"))
        self.labelMatchPercentageTitle.setText(_translate("MainWindow", "Match % (within tol.)"))
        self.labelMatchPercentageValue.setText(_translate("MainWindow", "--"))
        self.labelPerSignalBreakdownTitle.setText(_translate("MainWindow", "Per-Signal Breakdown"))
        self.labelPerSignalBreakdownTitle.setStyleSheet(_translate("MainWindow", "font-weight: bold;"))
        self.labelWorstMismatchesTitle.setText(_translate("MainWindow", "Worst Mismatched Samples"))
        self.labelWorstMismatchesTitle.setStyleSheet(_translate("MainWindow", "font-weight: bold;"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabStatistics), _translate("MainWindow", "📊  Statistics"))
        self.labelVoltagePlotTitle.setText(_translate("MainWindow", "Voltage — Digital Twin vs ECU"))
        self.labelVoltageWarning.setStyleSheet(_translate("MainWindow", "color: #d32f2f; font-weight: bold;"))
        self.labelCurrentPlotTitle.setText(_translate("MainWindow", "Current — Digital Twin vs ECU"))
        self.labelCurrentWarning.setStyleSheet(_translate("MainWindow", "color: #d32f2f; font-weight: bold;"))
        self.labelTemperaturePlotTitle.setText(_translate("MainWindow", "Temperature — Digital Twin vs ECU"))
        self.labelSocPlotTitle.setText(_translate("MainWindow", "SoC — Digital Twin vs ECU"))
        self.labelSohPlotTitle.setText(_translate("MainWindow", "SoH — Digital Twin vs ECU"))
        self.groupBoxSignalSelection.setTitle(_translate("MainWindow", "Signals to Include in Error Graph"))
        self.checkBoxSignalVoltage.setText(_translate("MainWindow", "Voltage"))
        self.checkBoxSignalCurrent.setText(_translate("MainWindow", "Current"))
        self.checkBoxSignalTemperature.setText(_translate("MainWindow", "Temperature"))
        self.checkBoxSignalSoc.setText(_translate("MainWindow", "SoC"))
        self.checkBoxSignalSoh.setText(_translate("MainWindow", "SoH"))
        self.checkBoxSignalSelectOnly.setText(_translate("MainWindow", "Select only one"))
        self.labelErrorPlotTitle.setText(_translate("MainWindow", "Error Over Time (ECU − Digital Twin)"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabGraphs), _translate("MainWindow", "📈  Graphs / Overlay"))
        self.groupBoxTolerance.setTitle(_translate("MainWindow", "Tolerance Thresholds (%)"))
        self.labelVoltageToleranceCaption.setText(_translate("MainWindow", "Voltage Tolerance (%)"))
        self.labelCurrentToleranceCaption.setText(_translate("MainWindow", "Current Tolerance (%)"))
        self.labelTemperatureToleranceCaption.setText(_translate("MainWindow", "Temperature Tolerance (%)"))
        self.groupBoxThresholdWarnings.setTitle(_translate("MainWindow", "⚠  Threshold Warnings"))
        self.checkBoxEnableVoltageThreshold.setText(_translate("MainWindow", "Warn when Voltage exceeds"))
        self.doubleSpinBoxVoltageThreshold.setSuffix(_translate("MainWindow", " V"))
        self.checkBoxEnableCurrentThreshold.setText(_translate("MainWindow", "Warn when Current exceeds"))
        self.doubleSpinBoxCurrentThreshold.setSuffix(_translate("MainWindow", " A"))
        self.groupBoxAlignment.setTitle(_translate("MainWindow", "Timebase Alignment Method"))
        self.comboBoxAlignmentMethod.setItemText(0, _translate("MainWindow", "Nearest Timestamp"))
        self.comboBoxAlignmentMethod.setItemText(1, _translate("MainWindow", "Linear Interpolation"))
        self.btnApplyRerun.setText(_translate("MainWindow", "Apply & Re-run Comparison"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabConfig), _translate("MainWindow", "⚙  Config / Tolerance"))
        self.groupBoxExportReport.setTitle(_translate("MainWindow", "Export Full Comparison Report"))
        self.labelReportFormatCaption.setText(_translate("MainWindow", "Format:"))
        self.comboBoxReportFormat.setItemText(0, _translate("MainWindow", "PDF"))
        self.comboBoxReportFormat.setItemText(1, _translate("MainWindow", "HTML"))
        self.btnExportReport.setText(_translate("MainWindow", "Export Report..."))
        self.groupBoxExportData.setTitle(_translate("MainWindow", "Export Raw Aligned Comparison Table"))
        self.labelDataFormatCaption.setText(_translate("MainWindow", "Format:"))
        self.comboBoxDataFormat.setItemText(0, _translate("MainWindow", "CSV"))
        self.comboBoxDataFormat.setItemText(1, _translate("MainWindow", "Excel"))
        self.btnExportData.setText(_translate("MainWindow", "Export Table..."))
        self.labelExportLogTitle.setText(_translate("MainWindow", "Export Log"))
        self.labelExportLogTitle.setStyleSheet(_translate("MainWindow", "font-weight: bold;"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabReport), _translate("MainWindow", "📄  Report / Export"))
        self.labelLiveModeInfo.setText(_translate("MainWindow", "Live mode streams both the Digital Twin output and the ECU output over MQTT and feeds them into the same comparison engine used for offline CSV comparison. Connect to the broker, then incoming samples populate the Preview, Statistics, and Graphs tabs in real time."))
        self.groupBoxMqttBroker.setTitle(_translate("MainWindow", "MQTT Broker"))
        self.labelMqttHostCaption.setText(_translate("MainWindow", "Broker Host / IP:"))
        self.lineEditMqttHost.setPlaceholderText(_translate("MainWindow", "localhost"))
        self.labelMqttPortCaption.setText(_translate("MainWindow", "Port:"))
        self.labelMqttQosCaption.setText(_translate("MainWindow", "QoS:"))
        self.comboBoxMqttQos.setItemText(0, _translate("MainWindow", "0 — At most once"))
        self.comboBoxMqttQos.setItemText(1, _translate("MainWindow", "1 — At least once"))
        self.comboBoxMqttQos.setItemText(2, _translate("MainWindow", "2 — Exactly once"))
        self.labelMqttUserCaption.setText(_translate("MainWindow", "Username (opt.):"))
        self.lineEditMqttUser.setPlaceholderText(_translate("MainWindow", "(anonymous)"))
        self.labelMqttPassCaption.setText(_translate("MainWindow", "Password (opt.):"))
        self.lineEditMqttPass.setPlaceholderText(_translate("MainWindow", "(none)"))
        self.groupBoxMqttTopics.setTitle(_translate("MainWindow", "MQTT Topic Roots"))
        self.labelMqttTwinTopicCaption.setText(_translate("MainWindow", "Digital Twin topic:"))
        self.lineEditMqttTwinTopic.setText(_translate("MainWindow", "bms/twin/#"))
        self.labelMqttEcuTopicCaption.setText(_translate("MainWindow", "ECU topic:"))
        self.lineEditMqttEcuTopic.setText(_translate("MainWindow", "bms/actual/#"))
        self.groupBoxLiveUpdate.setTitle(_translate("MainWindow", "Live Update"))
        self.checkBoxLiveAutoRefresh.setText(_translate("MainWindow", "Auto-refresh (re-run align + statistics on a timer)"))
        self.labelLiveIntervalCaption.setText(_translate("MainWindow", "Refresh interval:"))
        self.labelLiveIntervalUnit.setText(_translate("MainWindow", "ms"))
        self.btnLiveConnect.setText(_translate("MainWindow", "Connect Live Stream"))
        self.labelLiveStatus.setText(_translate("MainWindow", "Status: Disconnected"))
        self.btnLiveSnapshot.setText(_translate("MainWindow", "Freeze & Take Snapshot"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabLiveMode), _translate("MainWindow", "📡  Live (MQTT)"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabEvents), _translate("MainWindow", "🚨  Events"))
from pyqtgraph import PlotWidget
